### PR TITLE
Panic hunting and `cargo fuzz` for `Packet::parse`

### LINKED ISSUE #457: Don't panic on malformed packets.
Recently saw the following panic on a test rack.

```
> ::status
debugging crash dump vmcore.0 (64-bit) from BRM42220013
operating system: 5.11 helios-2.0.22466 (oxide)
build version: heads/stlouis-0-g3621450307

image uuid: 1a8bea08-4d63-44cf-b11d-50ef61d285ba
panic message: panicked at lib/opte/src/engine/ip6.rs:165:13:
assertion failed: ext_len <= 64
dump content: kernel pages only
  (curproc requested, but a kernel thread panicked)
```

This assertion appears to be due to the fact that the packet we're trying to parse is corrupted.

```
> $C
fffff7881273b240 vpanic()
fffff7881273b2d0 rust_begin_unwind+0x117()
fffff7881273b310 core::panicking::panic_fmt::h819335437b3690a9+0x2f()
fffff7881273b360 core::panicking::panic::h1c040510b92182b9+0x44()
fffff7881273b470 <opte::engine::ip6::Ipv6Meta as core::convert::From<&opte::engine::ip6::Ipv6Hdr>>::from::hc63a92d43f1cf5ea+0x290()
fffff7881273b540 opte::engine::packet::Packet<opte::engine::packet::Initialized>::parse_ip6::hd2529136a56ae8fe+0x97()
fffff7881273ba60 <oxide_vpc::engine::VpcParser as opte::engine::NetworkParser>::parse_inbound::h04dc83c2aefcf4b4+0x137()
fffff7881273c2b0 opte::engine::packet::Packet<opte::engine::packet::Initialized>::wrap_mblk_and_parse::hf918f36dab09e624+0x9b()
fffff7881273c930 xde_rx+0x5a()
fffff7881273c980 mac_promisc_dispatch_one+0x60(fffffcfa5d93dee8, fffffcfb6fe48f40, 0, 0)
fffff7881273ca00 mac_promisc_dispatch+0x83(fffffcfa3a46b010, fffffcfb6fe48f40, 0, 0)
fffff7881273ca60 mac_rx_common+0x47(fffffcfa3a46b010, fffffcfa3f5eecb0, fffffcfb6fe48f40)
fffff7881273cac0 mac_rx+0xc6(fffffcfa3a46b010, fffffcfa3f5eecb0, fffffcfb6fe48f40)
fffff7881273cb00 mac_rx_ring+0x2b(fffffcfa3a46b010, fffffcfa3f5eecb0, fffffcfb6fe48f40, 1)
fffff7881273cb40 t4_intr_rx_work+0xb4(fffffcfa344ba800)
fffff7881273cb80 t4_intr+0x5d(fffffcfa2e2b9000, fffffcfa344ba800)
fffff7881273cbd0 apix_dispatch_by_vector+0x8c(20)
fffff7881273cc00 apix_dispatch_lowlevel+0x29(20, 0)
fffff788126eba40 switch_sp_and_call+0x15()
fffff788126ebaa0 apix_do_interrupt+0xf2(fffff788126ebab0, 0)
fffff788126ebab0 _interrupt+0xc3()
fffff788126ebba0 i86_mwait+0x12()
fffff788126ebbd0 cpu_idle_mwait+0x14b()
fffff788126ebbe0 cpu_idle_adaptive+0x19()
fffff788126ebc00 idle+0xa8()
fffff788126ebc10 thread_start+0xb()
```
```
> fffffcfb6fe48f40::print mblk_t
{
    b_next = 0
    b_prev = 0
    b_cont = 0
    b_rptr = 0xfffffd076404cc02
    b_wptr = 0xfffffd076404ce63
    b_datap = 0xfffffcfb815aae00
    b_band = 0
    b_tag = 0
    b_flag = 0
    b_queue = 0
}
```
```
> 0xfffffd076404cc02::dump -l 0t609
                    0 1\/ 3  4 5 6 7  8 9 a b  c d e f  01v3456789abcdef
fffffd076404cc00:  0000a840 250401d4 a8402505 151186dd  ...@%....@%.....
fffffd076404cc10:  00c80800 60000000 022711fe 00000000  ....`....'......
fffffd076404cc20:  00000000 00000000 00000000 fd001122  ..............."
fffffd076404cc30:  33440111 00000000 00000001 17c117c1  3D..............
fffffd076404cc40:  0227cf4e 01006558 00006400 01290000  .'.N..eX..d..)..
fffffd076404cc50:  a84025ff e85f0000 00000000 81004500  .@%.._........E.
fffffd076404cc60:  0205e080 40003706 1a9fc6d3 7a402d9a  ....@.7.....z@-.
fffffd076404cc70:  d825a122 01bbad22 5193a5f8 01588018  .%."..."Q....X..
fffffd076404cc80:  01260224 00000101 080a48d7 9a230431  .&.$......H..#.1
fffffd076404cc90:  9f431403 03000101 17030300 45f6cde2  .C..........E...
fffffd076404cca0:  c1e5a065 a7fe29a8 a2b05791 7eacc834  ...e..)...W.~..4
fffffd076404ccb0:  dd6bfa21 f0895d12 90ba323a 007a4dc8  .k.!..]...2:.zM.
fffffd076404ccc0:  11bff0ab 126910d1 ebb35894 efda1146  .....i....X....F
fffffd076404ccd0:  ea3b72d8 8efb958c 26ad84fb 812869e3  .;r.....&....(i.
fffffd076404cce0:  5fe71703 03017cec a43fca9c 1818997a  _.....|..?.....z
fffffd076404ccf0:  706ff3de 584f1a40 2bc6f7aa 4371d7df  po..XO.@+...Cq..
fffffd076404cd00:  e7741893 3a3a9af4 9dd276d0 0038cea0  .t..::....v..8..
fffffd076404cd10:  277b26eb cc3bfdb6 91f8f949 5c08dbf7  '{&..;.....I\...
fffffd076404cd20:  ccc4e91b fd2b5c54 6f7ea278 9813966c  .....+\To~.x...l
fffffd076404cd30:  e333345a 937ff4b0 f6432f03 82392158  .34Z.....C/..9!X
fffffd076404cd40:  e0d5c8a5 59cff56a 74524f57 5645a363  ....Y..jtROWVE.c
fffffd076404cd50:  76d993f3 261f861d e13fc76a c6d9d1d2  v...&....?.j....
fffffd076404cd60:  e5d588e0 594f313c 8be401ce cb5627d7  ....YO1<.....V'.
fffffd076404cd70:  c61f51a0 4c697892 50096d2d 31d13063  ..Q.Lix.P.m-1.0c
fffffd076404cd80:  3bcce092 ceb47851 139fe4c9 cb48ad91  ;.....xQ.....H..
fffffd076404cd90:  e274e9ea 5b146ba7 0244a43b cdc91178  .t..[.k..D.;...x
fffffd076404cda0:  929e1713 f9d23664 8c2e35a7 e69be049  ......6d..5....I
fffffd076404cdb0:  528f035a 410c5668 5a189856 234f232a  R..ZA.VhZ..V#O#*
fffffd076404cdc0:  f4b9ad4b 16f13e87 f80afc38 f9654a31  ...K..>....8.eJ1
fffffd076404cdd0:  69e7cea9 cc0a22ea cc6d91ba 4e69c59c  i....."..m..Ni..
fffffd076404cde0:  fe24fe88 bff695b5 2ff330d4 3458c8bf  .$....../.0.4X..
fffffd076404cdf0:  acf6a1f6 5f1e0c15 297b9506 37a72cab  ...._...){..7.,.
fffffd076404ce00:  7e48c4de 4bf5ead0 e0511f7c b28addc1  ~H..K....Q.|....
fffffd076404ce10:  3c733288 4325aca7 a895ebe7 8e7f0ec1  <s2.C%..........
fffffd076404ce20:  fd5d221c f1fd95de 21cbe124 e474754a  .]".....!..$.tuJ
fffffd076404ce30:  ebd68877 4977f85b abab377c bb75e244  ...wIw.[..7|.u.D
fffffd076404ce40:  de285805 132535c0 33387351 5242a1f1  .(X..%5.38sQRB..
fffffd076404ce50:  eb57e076 e11a2ea7 1e5a4099 8f254a50  .W.v.....Z@..%JP
fffffd076404ce60:  9252e600 00000000 c6d767b5 b98bdb31  .R........g....1
```

Taking a look at just the first two lines

```
fffffd076404cc00:  0000a840 250401d4 a8402505 151186dd  ...@%....@%.....
fffffd076404cc10:  00c80800 60000000 022711fe 00000000  ....`....'......
```

The mac addresses in the ethernet header appear to be offset by two bytes. There is an ipv6 ethertype there, but what directly follows is not a v6 packet, there's 4 bytes of junk before we reach a `6` indicating we _may_ be at the front of a v6 header. Later on there are what appear to be v6 oxide underlay addresses. But at any rate, this packet appears to be malformed and we should not have an `assert` here.

### PR DESCRIPTION
**Pull request by FelixMcFelix**
This PR introduces a basic fuzz-testing framework for `VpcParser` in addition to fixing some panics -- both known and unknown!

Sadly, `cargo fuzz` via libFuzzer only works on a) nightly, b) Mac/Linux and not illumos. What we have instead to make up somewhat is a fairly simple harness to store bad packets, label and describe them, and run them as part of the wider `cargo test`.

Fixes #457 as well as:
* A negative slice length overflow in DDM v6 extension parsing,
* Bad IPv4 `total_len`s resulting in negative overflow of packet body length,
* IPv4 IHL longer than packet body would cause negative overflow on offset computation.

### CODE REVIEW

File: lib/oxide-vpc/tests/fuzz_regression.rs [hunk 1]
```diff
@@ -0,0 +1,130 @@
...
+            path.file_stem().and_then(OsStr::to_str).unwrap_or("<unlabelled>");
+
+        tests.extend(
+            cases
+                .into_iter()
+                .map(|(name, v)| (Label { family: family.into(), name }, v)),
+        )
+    }
+
+    // Run all captured tests.
```
Comment (rcgoodfellow) [inline lib/oxide-vpc/tests/fuzz_regression.rs:77]: I like this approach of sending known bad packets through to catch regressions.

**Review by rcgoodfellow — APPROVED** [review]
