### PR TITLE
squash headers into single segment during parsing

### LINKED ISSUE #349: panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd'
In attempting to test https://github.com/oxidecomputer/omicron/pull/2419, `ping 8.8.8.8` inside the `oxz_nexus` zone caused the host to panic:

```
> ::status
debugging crash dump vmcore.0 (64-bit) from frostypaws
operating system: 5.11 helios-1.0.21472 (i86pc)
build version: heads/master-0-g8b0ccc49c4

image uuid: a0c9f249-7085-cf8c-cb43-c7afc06abcfa
panic message: panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd', /home/james/opte/opte/src/engine/packet.rs:1258:17
dump content: kernel pages only
```

The panic is from the following unwrap:

https://github.com/oxidecomputer/opte/blob/b274cad9e981cbb7de1d3a48834b1f97500a13a8/opte/src/engine/packet.rs#L1239-L1258

Digging into the `vmcore` to pull out the packet:

```
> $C
fffffe00f84d5be0 vpanic()
fffffe00f84d5c70 rust_begin_unwind+0x146()
fffffe00f84d5cb0 core::panicking::panic_fmt::h1f3af2ce034ff287+0x2d()
fffffe00f84d5d30 core::result::unwrap_failed::hffd399f398414a08+0x6c()
fffffe00f84d5e80 opte::engine::packet::Packet<opte::engine::packet::Parsed>::emit_new_headers::h173e737837736234+0x117e()
fffffe00f84d62f0 opte::engine::port::Port<N>::process::h0082486ad0ade07f+0x199d()
fffffe00f84d6c20 xde_mc_tx+0x32f()
fffffe00f84d6c50 mac_ring_tx+0x43(fffffeb31905d038, 0, fffffeb2b61b9180)
<snip>

> fffffeb2b61b9180::walk b_cont mblk_t | ::mblk  
            ADDR FL TYPE    LEN   BLEN              RPTR             DBLK
fffffeb2b61b9180 0  data    14    16    fffffeb2da36cd70 fffffeb2da36cd00
fffffeb2b58a21c0 0  data    84    144   fffffeb296a50290 fffffeb296a50200

> fffffeb2da36cd70::dump -u -l 0xe -t -g 1
                    0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f  0123456789abcdef
fffffeb2da36cd70:  a8 40 25 ff 77 77 a8 40  25 ff 00 01 08 00        .@%.ww.@%.....  

> fffffeb296a50290::dump -u -l 0x54 -t -g 1
                    0  1  2  3  4  5  6  7   8  9  a  b  c  d  e  f  0123456789abcdef
fffffeb296a50290:  45 00 00 54 00 03 40 00  ff 01 61 91 0a 00 00 05  E..T..@...a.....
fffffeb296a502a0:  08 08 08 08 08 00 b9 8f  0e e8 00 00 f9 eb 07 64  ...............d
fffffeb296a502b0:  3f 35 04 00 08 09 0a 0b  0c 0d 0e 0f 10 11 12 13  ?5..............
fffffeb296a502c0:  14 15 16 17 18 19 1a 1b  1c 1d 1e 1f 20 21 22 23  ............ !"#
fffffeb296a502d0:  24 25 26 27 28 29 2a 2b  2c 2d 2e 2f 30 31 32 33  $%&'()*+,-./0123
fffffeb296a502e0:  34 35 36 37                                       4567
```

Reassembling this packet into a format wireshark can import:

```
I 2023-03-08T15:53:49Z
00000000: a8 40 25 ff 77 77 a8 40 25 ff 00 01 08 00 45 00
00000010: 00 54 00 03 40 00 ff 01 61 91 0a 00 00 05 08 08
00000020: 08 08 08 00 b9 8f 0e e8 00 00 f9 eb 07 64 3f 35
00000030: 04 00 08 09 0a 0b 0c 0d 0e 0f 10 11 12 13 14 15
00000040: 16 17 18 19 1a 1b 1c 1d 1e 1f 20 21 22 23 24 25
00000050: 26 27 28 29 2a 2b 2c 2d 2e 2f 30 31 32 33 34 35
00000060: 36 37
```

shows that this is the ping packet:

```
Frame 1: 98 bytes on wire (784 bits), 98 bytes captured (784 bits) on interface unknown, id 0
    Interface id: 0 (unknown)
        Interface name: unknown
    Encapsulation type: Ethernet (1)
    Arrival Time: Mar  8, 2023 10:58:36.000001000 EST
    [Time shift for this packet: 0.000000000 seconds]
    Epoch Time: 1678291116.000001000 seconds
    [Time delta from previous captured frame: 0.000000000 seconds]
    [Time delta from previous displayed frame: 0.000000000 seconds]
    [Time since reference or first frame: 0.000000000 seconds]
    Frame Number: 1
    Frame Length: 98 bytes (784 bits)
    Capture Length: 98 bytes (784 bits)
    [Frame is marked: False]
    [Frame is ignored: False]
    [Protocols in frame: eth:ethertype:ip:icmp:data]
    [Coloring Rule Name: ICMP]
    [Coloring Rule String: icmp || icmpv6]
Ethernet II, Src: OxideCom_ff:00:01 (a8:40:25:ff:00:01), Dst: OxideCom_ff:77:77 (a8:40:25:ff:77:77)
    Destination: OxideCom_ff:77:77 (a8:40:25:ff:77:77)
        Address: OxideCom_ff:77:77 (a8:40:25:ff:77:77)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Source: OxideCom_ff:00:01 (a8:40:25:ff:00:01)
        Address: OxideCom_ff:00:01 (a8:40:25:ff:00:01)
        .... ..0. .... .... .... .... = LG bit: Globally unique address (factory default)
        .... ...0 .... .... .... .... = IG bit: Individual address (unicast)
    Type: IPv4 (0x0800)
Internet Protocol Version 4, Src: 10.0.0.5, Dst: 8.8.8.8
    0100 .... = Version: 4
    .... 0101 = Header Length: 20 bytes (5)
    Differentiated Services Field: 0x00 (DSCP: CS0, ECN: Not-ECT)
        0000 00.. = Differentiated Services Codepoint: Default (0)
        .... ..00 = Explicit Congestion Notification: Not ECN-Capable Transport (0)
    Total Length: 84
    Identification: 0x0003 (3)
    Flags: 0x40, Don't fragment
        0... .... = Reserved bit: Not set
        .1.. .... = Don't fragment: Set
        ..0. .... = More fragments: Not set
    ...0 0000 0000 0000 = Fragment Offset: 0
    Time to Live: 255
    Protocol: ICMP (1)
    Header Checksum: 0x6191 [validation disabled]
    [Header checksum status: Unverified]
    Source Address: 10.0.0.5
    Destination Address: 8.8.8.8
Internet Control Message Protocol
    Type: 8 (Echo (ping) request)
    Code: 0
    Checksum: 0xb98f [correct]
    [Checksum Status: Good]
    Identifier (BE): 3816 (0x0ee8)
    Identifier (LE): 59406 (0xe80e)
    Sequence Number (BE): 0 (0x0000)
    Sequence Number (LE): 0 (0x0000)
    [No response seen]
        [Expert Info (Warning/Sequence): No response seen to ICMP request]
            [No response seen to ICMP request]
            [Severity level: Warning]
            [Group: Sequence]
    Timestamp from icmp data: Mar  7, 2023 20:59:21.275775000 EST
    [Timestamp from icmp data (relative): 50354.724226000 seconds]
    Data (48 bytes)
        Data: 08090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f202122232425262728292a2b…
        [Length: 48]
```

### LINKED ISSUE #351: Panic on `shrink_start` in `hdr_seg`
We are hitting a panic in testing at the following location.

https://github.com/oxidecomputer/opte/blob/fa5c759d0e4575cb6cff227831193dd2df657d5f/opte/src/engine/packet.rs#L1308

```
panic[cpu35]/thread=fffffd3a3dcf4020: panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd', /work/oxidecomputer/opte/opte/src/engine/packet.rs:1308:17
fffff8674aa24cf0 xde:rust_begin_unwind+146 ()
fffff8674aa24d30 xde:_ZN4core9panicking9panic_fmt17hbd42276bcaa2dfd8E+2d ()
fffff8674aa24db0 xde:_ZN4core6result13unwrap_failed17h5b67be868f6dc91bE+6c ()
fffff8674aa24f00 xde:_ZN4opte6engine6packet42Packet$LT$opte..engine..packet..Parsed$GT$16emit_new_headers17h6228ac001b3d4500E+125c ()
fffff8674aa25310 xde:_ZN4opte6engine4port13Port$LT$N$GT$7process17h9bca109443cf9deaE+2544 ()
fffff8674aa25c40 xde:xde_mc_tx+32f ()
fffff8674aa25c70 mac:mac_ring_tx+43 ()
fffff8674aa25cc0 mac:mac_provider_tx+85 ()
fffff8674aa25d80 mac:mac_tx+295 ()
fffff8674aa25e10 dld:proto_unitdata_req+273 ()
fffff8674aa25e60 dld:dld_wput+a9 ()
fffff8674aa25ed0 unix:putnext+233 ()
fffff8674aa25fe0 ip:ip_xmit+632 ()
fffff8674aa26070 ip:nce_resolv_ok+fa ()
fffff8674aa260f0 ip:ip_nce_resolve_all+ef ()
...
```

CC: @leftwo @luqmana @bnaecker

### PR DESCRIPTION
**Pull request by rcgoodfellow**
This PR fixes the issue described in the following [comment](https://github.com/oxidecomputer/opte/blob/master/opte/src/engine/packet.rs#L1292-L1307). 

```
XXX This assumes that the headers all reside in the
first segment. For any typical implementation, this
should be true (it's better for performance, and
just makes the most sense). However, if that
invariant doesn't hold true, this method of erasing
the original header data is incomplete. It will
only partially erase the data, leading to confusion
downstream somewhere. The best solution is to check
for this during parsing. If the header straddles
segments, then just copy all header data into a new
segment, and replace the old header data with that
one segment. This means a hit on performance, but
it also means sanity for all downstream code.
Besides, any network stack that cares about
performance will already make sure to place the
headers in a single buffer.
```

This has resulted in panics in a few different environments.

This patch takes the advice of the comment and squashes the headers down into a single segment during parsing.

## Testing

A test is also added that captures the panic behavior.

### Without patch

```
ry@masaka:~/src/opte/oxide-vpc$ RUST_BACKTRACE=1 cargo test snat_icmp4_echo_rewrite
    Finished test [unoptimized + debuginfo] target(s) in 0.07s
     Running unittests src/lib.rs (target/debug/deps/oxide_vpc-09fa660a95f8ab19)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.00s

     Running tests/firewall_tests.rs (target/debug/deps/firewall_tests-e22257a8a15a7116)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/debug/deps/integration_tests-8e7dfa9921effefa)

running 1 test
test snat_icmp4_echo_rewrite ... FAILED

failures:

---- snat_icmp4_echo_rewrite stdout ----
thread 'snat_icmp4_echo_rewrite' panicked at 'called `Result::unwrap()` on an `Err` value: StartPastEnd', /home/ry/src/opte/opte/src/engine/packet.rs:1392:51
stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::result::unwrap_failed
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1113:23
   4: opte::engine::packet::Packet<opte::engine::packet::Parsed>::hdr_seg
             at /home/ry/src/opte/opte/src/engine/packet.rs:1392:17
   5: opte::engine::packet::Packet<opte::engine::packet::Parsed>::emit_new_headers
             at /home/ry/src/opte/opte/src/engine/packet.rs:1494:9
   6: opte::engine::port::Port<N>::process
             at /home/ry/src/opte/opte/src/engine/port.rs:1112:13
   7: integration_tests::snat_icmp4_echo_rewrite
             at ./tests/integration_tests.rs:990:15
   8: integration_tests::snat_icmp4_echo_rewrite::{{closure}}
             at ./tests/integration_tests.rs:956:1
   9: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    snat_icmp4_echo_rewrite

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 23 filtered out; finished in 0.05s

error: test failed, to rerun pass `--test integration_tests`
```

### With patch

```
ry@masaka:~/src/opte/oxide-vpc$ RUST_BACKTRACE=1 cargo test snat_icmp4_echo_rewrite
   Compiling opte v0.1.0 (/home/ry/src/opte/opte)
   Compiling oxide-vpc v0.1.0 (/home/ry/src/opte/oxide-vpc)
    Finished test [unoptimized + debuginfo] target(s) in 6.85s
     Running unittests src/lib.rs (target/debug/deps/oxide_vpc-09fa660a95f8ab19)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 6 filtered out; finished in 0.00s

     Running tests/firewall_tests.rs (target/debug/deps/firewall_tests-e22257a8a15a7116)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 3 filtered out; finished in 0.00s

     Running tests/integration_tests.rs (target/debug/deps/integration_tests-8e7dfa9921effefa)

running 1 test
test snat_icmp4_echo_rewrite ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 23 filtered out; finished in 0.01s
```

Fixes #349 
Fixes #351

### CODE REVIEW

File: opte/src/engine/packet.rs [hunk 1]
```diff
@@ -751,19 +751,98 @@ impl Packet<Initialized> {
...
+                    body,
+                    body_modified: false,
+                },
+            });
+        }
+
+        // Calculate the body offset within the new squashed segment
+        for s in &self.segs[..squash_to] {
+            body.seg_offset += s.len;
+        }
```
Comment (luqmana) [inline opte/src/engine/packet.rs:810]: Should this be conditional on `body.seg_offset > 0`?

File: opte/src/engine/packet.rs [hunk 2]
```diff
@@ -751,19 +751,98 @@ impl Packet<Initialized> {
...
+
         Ok(Packet {
             avail: self.avail,
             source: self.source,
-            // The new packet is taking ownership of the segments.
-            segs: core::mem::take(&mut self.segs),
+            segs,
             state: Parsed {
                 len: self.state.len,
                 hdr_offsets: info.offsets,
```
Comment (luqmana) [inline opte/src/engine/packet.rs:848]: All the header offsets in `info.offsets` need to be updated in this case.

File: oxide-vpc/tests/common/icmp.rs [hunk 3]
```diff
@@ -101,12 +109,40 @@ pub fn gen_icmp_echo(
...
+        wtr.write(&icmp_bytes).unwrap();
+        pkt.parse(Out, VpcParser::new()).unwrap()
+    } else {
+        let mut pkt = Packet::alloc_and_expand(EtherHdr::SIZE);
+        let mut wtr = pkt.seg_wtr(0);
+        eth.emit(wtr.slice_mut(EtherHdr::SIZE).unwrap());
+
+        /*
+         * TODO
+         * It seems like this should also work, but it does not. Leaving this as
```
Comment (luqmana) [inline oxide-vpc/tests/common/icmp.rs:127]: I think this is because of the missing `body.seg_offset > 0` check I mentioned above.

File: oxide-vpc/tests/common/icmp.rs [hunk 4]
```diff
@@ -140,10 +177,22 @@ pub fn gen_icmpv6_echo_req(
         &EtherMeta { dst: eth_dst, src: eth_src, ether_type: EtherType::Ipv6 };
```
Comment (luqmana) [inline oxide-vpc/tests/common/icmp.rs:177]: Github won't let me comment on it, but I just realized the line setting `pay_len` above has been wrong.

```rust
        pay_len: req.buffer_len() as u16,
```

Since you're already here mind fixing it?

Comment (luqmana) [inline oxide-vpc/tests/common/icmp.rs:177]: Github won't let me comment on it, but I just realized the line setting `pay_len` above has been wrong.

```rust
        pay_len: req.buffer_len() as u16,
```

Since you're already here mind fixing it?

**Review by luqmana — CHANGES_REQUESTED** [review]
Thanks for getting on this so quick!

File: opte/src/engine/packet.rs [hunk 5]
```diff
@@ -751,19 +751,98 @@ impl Packet<Initialized> {
...
+
+        // Determine how big the message block for the squashed segment needs to
+        // be.
+        let mut new_seg_size = 0;
+        for s in &self.segs[..squash_to + 1] {
+            new_seg_size += s.len;
+        }
+
+        // Allocate a message block and copy in the squashed data.
+        let mut mp = allocb(new_seg_size);
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Good call. Done.

File: opte/src/engine/packet.rs [hunk 6]
```diff
@@ -751,19 +751,98 @@ impl Packet<Initialized> {
...
+                    (*mp).b_wptr,
+                    s.len,
+                );
+                (*mp).b_wptr = (*mp).b_wptr.add(s.len);
+            }
+        }
+
+        // Construct a new segment vector, tacking on any remaining segments
+        // after the header segments.
+        let orig_segs = core::mem::take(&mut self.segs);
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:845]: Took a swing at fixing this. Will test on Linux in the morning.

File: opte/src/engine/packet.rs (hunk 1 above)
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Yup. Fixed

File: opte/src/engine/packet.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: `wrap_mblk` seems to expect the `b_wptr` of the passed in `mblk_t` to already be set in order to have the segment length set correctly.

**Review by luqmana — CHANGES_REQUESTED** [review]

File: opte/src/engine/packet.rs (hunk 2 above)
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:867]: Done

File: opte/src/engine/packet.rs [hunk 7]
```diff
@@ -751,19 +751,112 @@ impl Packet<Initialized> {
...
+
+        // Allocate a message block and copy in the squashed data. Provide
+        // enough extra space for genve encapsulation to not require an extra
+        // allocation later on. 128 is based on
+        // - 18 byte ethernet header (vlan space)
+        // - 40 byte ipv6 header
+        // - 8 byte udp header
+        // - 8 byte geneve header
+        // - space for geneve options
+        const EXTRA_SPACE: usize = 128;
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Done.

File: opte/src/engine/packet.rs [hunk 8]
```diff
@@ -751,19 +751,112 @@ impl Packet<Initialized> {
...
+        let mut mp = allocb(new_seg_size + EXTRA_SPACE);
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Done

File: opte/src/engine/packet.rs [hunk 9]
```diff
@@ -751,19 +751,98 @@ impl Packet<Initialized> {
...
+        let orig_segs = core::mem::take(&mut self.segs);
+        let mut segs = vec![unsafe { PacketSeg::wrap_mblk(mp) }];
+        if squash_to + 1 < orig_segs.len() {
+            segs[0].link(&orig_segs[squash_to + 1]);
+            segs.extend_from_slice(&orig_segs[squash_to + 1..]);
+        }
+
         Ok(Packet {
             avail: self.avail,
             source: self.source,
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:863]: Yeah, I'm not quite sure what the correct value is here.

[the remark this answers is not in the document]
Comment (luqmana) [reply opte/src/engine/packet.rs:863]: hmm yea, i'd say maybe just remove em or open an issue for later.

File: opte/src/engine/packet.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (luqmana) [reply opte/src/engine/packet.rs]: ah didn't catch that, nvm then

File: opte/src/engine/packet.rs [hunk 10]
```diff
@@ -751,19 +753,115 @@ impl Packet<Initialized> {
...
+                mock_freeb(s.mp);
+            }
+        }
+
+        // Recompute info after squash.
+        self.segs = core::mem::take(&mut segs);
+        let mut rdr = self.get_rdr_mut();
+        let info = match dir {
+            Direction::Out => net.parse_outbound(&mut rdr)?,
+            Direction::In => net.parse_inbound(&mut rdr)?,
```
Comment (luqmana) [inline opte/src/engine/packet.rs:857]: a bit unfortunate to have to re-parse here. why not update the offsets in-place?

File: oxide-vpc/src/engine/mod.rs [hunk 11]
```diff
@@ -212,9 +217,24 @@ impl NetworkParser for VpcParser {
...
 
+        // Allocate a message block and copy in the squashed data. Provide
+        // enough extra space for genve encapsulation to not require an extra
+        // allocation later on. 128 is based on
+        // - 18 byte ethernet header (vlan space)
+        // - 40 byte ipv6 header
+        // - 8 byte udp header
+        // - 8 byte geneve header
+        // - space for geneve options
+        const EXTRA_SPACE: Option<usize> = Some(128);
```
Comment (luqmana) [inline oxide-vpc/src/engine/mod.rs:228]: Move a bit up and use in ARP case above too

File: opte/src/engine/packet.rs (hunk 6 above)
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:841]: Done `lsan` coming back clean now.

File: oxide-vpc/tests/common/icmp.rs [hunk 12]
```diff
@@ -133,17 +154,29 @@ pub fn gen_icmpv6_echo_req(
...
+        pkt.parse(Out, VpcParser::new()).unwrap()
+    } else {
+        let mut pkt = Packet::alloc_and_expand(EtherHdr::SIZE);
+        let mut wtr = pkt.seg_wtr(0);
+        eth.emit(wtr.slice_mut(EtherHdr::SIZE).unwrap());
+        let i = pkt.add_seg(ip6.hdr_len() + body_bytes.len()).unwrap();
+        let mut wtr = pkt.seg_wtr(i);
+        ip6.emit(wtr.slice_mut(ip6.hdr_len()).unwrap());
+        wtr.write(&body_bytes).unwrap();
+        pkt.parse(Out, VpcParser::new()).unwrap()
```
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply oxide-vpc/tests/common/icmp.rs]: Done. 1, 2, and 3 segment variants are now there and are all exercised.

File: opte/src/engine/packet.rs (hunk 10 above)
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Changed to update in place.

File: oxide-vpc/src/engine/mod.rs (hunk 11 above)
Comment (rcgoodfellow) [reply oxide-vpc/src/engine/mod.rs]: Done

File: opte/src/engine/packet.rs (hunk 9 above)
[the remark this answers is not in the document]
Comment (rcgoodfellow) [reply opte/src/engine/packet.rs]: Removed

File: opte/src/engine/packet.rs [hunk 13]
```diff
@@ -751,19 +736,124 @@ impl Packet<Initialized> {
...
+            segs[0].link(&orig_segs[squash_to + 1]);
+            segs.extend_from_slice(&orig_segs[squash_to + 1..]);
+        }
+        #[cfg(any(feature = "std", test))]
+        for s in &orig_segs[..squash_to + 1] {
+            mock_freeb(s.mp);
+        }
+
+        let mut off = 0;
+        info.offsets.inner.ether.pkt_pos = 0;
```
Comment (luqmana) [inline opte/src/engine/packet.rs:835]: This doesn't account for any outer headers

Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:835]: We should only hit outer headers on inbound, in which case we won't hit the `shrink_start` path, so squashing does not matter. I've added a check to avoid squashing on the inbound case, so we don't need to worry about shifting around outer headers.

Comment (rcgoodfellow) [reply opte/src/engine/packet.rs:835]: Actually, scratch that we do hit `shrink_start` when new headers are smaller than old headers ... sigh.

Comment (luqmana) [reply opte/src/engine/packet.rs:835]: hmm, true but would we hit that case? `new_hdr_len > old_hdr_len` shouldn't be true in the inbound case right

Comment (luqmana) [reply opte/src/engine/packet.rs:835]: but i guess still no guarantee all the headers would be in the first segment

File: oxide-vpc/src/engine/mod.rs [hunk 14]
```diff
@@ -191,9 +191,24 @@ impl NetworkParser for VpcParser {
         offsets.inner.ether = ether_hi.offset;
         let ether_type = ether_hi.meta.ether_type;
 
+        // Allocate a message block and copy in the squashed data. Provide
+        // enough extra space for genve encapsulation to not require an extra
```
Comment (luqmana) [inline oxide-vpc/src/engine/mod.rs:195]: nit: geneve

**Review by luqmana — APPROVED** [review]
Thanks for fixing that up!

**Comment by rcgoodfellow** [comment]
Thanks for all the great feedback @luqmana
